spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://111.207.158.182:33306/cpaas?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.98.130:33306/cpaas?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Avaya123

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    #check-template: true
    #check-template-location: true
    #\u5F00\u542FMVC thymeleaf \u89C6\u56FE\u89E3\u6790
    #enabled: true
    #encoding: utf-8
    #mode: HTML5
    #prefix: classpath:/templates/
    #suffix: .html
    #resources:
    #  static-locations: classpath:/static/
    #mvc:
    #static-path-pattern: /static/**
  ##发邮件
  mail:
    host: smtp.163.com
    username: sunhoyu@163.com #自己的邮箱账号
    password: Avaya123  #这个不是登录密码而是163授权登录的密码
    default-encoding: UTF-8


  ##AD认证
  ldap:
    urls: ldaps://Ldap1.changhongit.com:636
    base: DC=changhongit,DC=com
    username: "administrator@changhongit.com"
    password: Avaya123



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





server:
  port: 8081

#debug: true
